# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyHttpAndJson' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyHttpAndJson
  pod 'Alamofire', '~> 4.4'
  pod 'EVReflection/MoyaRxSwift'
  pod 'SwiftyJSON'

  target 'MyHttpAndJsonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyHttpAndJsonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
